name: Node.js CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci -w @strawbang/api
      - run: npm run build -w @strawbang/api --if-present
      - run: npm test -w @strawbang/api
      - run: npm ci -w @strawbang/client
      - run: npm run build -w @strawbang/client --if-present
      - run: npm test -w @strawbang/client
